import "server-only";
import { canonicalBrowserSha256V2 } from "@/lib/custom-launch/browser-authority-v2";
import { projectionObject } from "@/lib/custom-launch/launch-projection-v1";

export const LAUNCH_CONTRACT_BASE_V1 = "https://api.programmable.market/v4/chains/4663/custom-launch-contract";
export type LaunchContractSetupV1 = { schemaVersion: "programmable.custom-launch-agent-setup.v1"; manifestDigest: string;
  requestSchemaVersion: "programmable.custom-launch-plan.v1"; text: string; guideUrl: string };

/** The setup is generated by the canonical manifest. A missing or mismatched artifact never asserts readiness. */
export async function readLaunchContractSetupV1(fetcher: typeof fetch = fetch): Promise<LaunchContractSetupV1> {
  const read = async (name: string) => {
    const response = await fetcher(`${LAUNCH_CONTRACT_BASE_V1}/${name}`, { redirect: "error", signal: AbortSignal.timeout(5000),
      headers: { accept: "application/json" }, next: { revalidate: 60 } });
    if (!response.ok || response.redirected || response.headers.get("content-type")?.split(";", 1)[0]?.trim() !== "application/json"
      || !response.body || Number(response.headers.get("content-length")) > 1048576) throw new Error("Launch contract unavailable");
    const reader = response.body!.getReader(); const chunks: Uint8Array[] = []; let size = 0;
    try { for (;;) { const { done, value } = await reader.read(); if (done) break; size += value.byteLength;
      if (size > 1048576) throw new Error("Launch contract exceeds the read budget"); chunks.push(value); }
    } finally { await reader.cancel().catch(() => undefined); reader.releaseLock(); }
    const value: unknown = JSON.parse(Buffer.concat(chunks).toString("utf8"));
    if (!projectionObject(value)) throw new Error("Invalid launch contract artifact");
    return value;
  };
  const [manifest, setup] = await Promise.all([read("manifest.json"), read("agent-setup.json")]);
  const { manifestDigest, ...body } = manifest;
  if (manifest.schemaVersion !== "programmable.custom-launch-contract.v1"
    || manifestDigest !== canonicalBrowserSha256V2("programmable.custom-launch-contract.v1", body)
    || setup.schemaVersion !== "programmable.custom-launch-agent-setup.v1" || setup.manifestDigest !== manifestDigest
    || setup.requestSchemaVersion !== "programmable.custom-launch-plan.v1" || typeof setup.text !== "string" || setup.text.length > 262144
    || !setup.text.includes(String(manifestDigest)) || typeof setup.guideUrl !== "string"
    || new URL(setup.guideUrl, "https://api.programmable.market").href !== `${LAUNCH_CONTRACT_BASE_V1}/guide.md`) {
    throw new Error("Launch setup and manifest digests differ");
  }
  return setup as LaunchContractSetupV1;
}
