import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";
import { encodeAbiParameters, parseAbiParameters } from "viem";
import { ModuleEngineBuilder } from "@/components/module-engine-builder";
import { ModuleEngineConsole } from "@/components/module-engine-console";
import { ModuleEngineTransactionReview } from "@/components/module-engine-transaction-review";
import { computeModuleEngineHostManifestHash } from "@/lib/module-engine/catalog";
import { ENGINE_OPERATIONS, prepareModuleEngineOperation } from "@/lib/module-engine/client";
import { moduleEngineUtcTimestamp } from "@/lib/module-engine/presentation";
import { fixture, ACCOUNT, QUOTE, TOKEN, addr, hash } from "./module-engine-fixture";

const actions = { wallet: { account: ACCOUNT, chainId: "4663", authenticated: true, sessionReady: true }, onConnect: vi.fn(), onSwitch: vi.fn(), onSubmit: vi.fn() };
describe("engine UI uses the existing wallet and reviewed configuration", () => {
  it("does not turn an unpublished source into an available launch", () => { const html = renderToStaticMarkup(<ModuleEngineBuilder {...actions} availability={{ schemaVersion: "programmable.module-engine.availability.v1", release: null, templates: [], reason: "Publication is pending." }} />); expect(html).toContain("Publication is pending."); expect(html).toContain("No reviewed template"); expect(html).not.toContain("Review launch"); });
  it("renders a general quote CA and shared schema fields without inventing a ticker list", () => { const f = fixture(); const html = renderToStaticMarkup(<ModuleEngineBuilder {...actions} {...f} />); expect(html).toContain('id="engine-quote"'); expect(html).toContain("exact ERC20 contract address"); expect(html).toContain("unlockTime"); expect(html).toContain("Check quote token"); expect(html).not.toContain("USDC"); });
  it("keeps the existing optional social links and blank image default", () => { const f = fixture(); const html = renderToStaticMarkup(<ModuleEngineBuilder {...actions} {...f} />); for (const key of ["twitter", "website", "telegram", "discord", "github", "gitbook"]) expect(html).toContain(`id="engine-social-${key}"`); expect(html).toContain("Add more links"); expect(html).toContain('id="engine-image"'); expect(html).toContain("Leave blank to use the Programmable token image."); });
  it("makes a fixed asset and fixed nested value readable but not editable", () => { const f = fixture(); const m = f.template.manifest.manifest; m.revision.fixedQuoteAsset = QUOTE; m.catalogDefinition.schema = { type: "record", required: ["unlockTime"], fields: { unlockTime: { type: "uint", binding: { mode: "fixed", value: "2000000000" } } } }; f.template.manifestHash = computeModuleEngineHostManifestHash(f.template.manifest); const html = renderToStaticMarkup(<ModuleEngineBuilder {...actions} {...f} />); expect(html).toContain(`readOnly=""`); expect(html).toContain(QUOTE); expect(html).toContain("Fixed by template"); expect(html).toContain("2000000000"); });
  it("shows the exact target, calldata, amount and nonce before the wallet callback", async () => { const f = fixture(); const prepared = await prepareModuleEngineOperation({ ...f, account: ACCOUNT, token: TOKEN }); if (prepared.kind !== "execute") throw new Error(); const confirm = vi.fn(); const html = renderToStaticMarkup(<ModuleEngineTransactionReview prepared={prepared} busy={false} onConfirm={confirm} onEdit={vi.fn()} />); expect(html).toContain(f.host); expect(html).toContain(prepared.transaction.data); expect(html).toContain("5000000"); expect(html).toContain("Account nonce"); expect(html).toContain("Confirm in wallet"); expect(confirm).not.toHaveBeenCalled(); });
  it("requires actual state before exposing deposit, fulfillment or refund controls", () => { const f = fixture(); const html = renderToStaticMarkup(<ModuleEngineConsole {...actions} {...f} token={TOKEN} />); expect(html).toContain("Refresh balances"); expect(html).not.toContain("Review deposit"); expect(html).not.toContain("Review fulfillment"); expect(html).not.toContain("Review ETH claim"); });
  it("reuses the existing image picker only through the host upload callback and preserves host slots", () => { const f = fixture(), upload = vi.fn(); const html = renderToStaticMarkup(<ModuleEngineBuilder {...actions} {...f} onUploadImage={upload} statusContent={<p>Recovery from the existing wallet</p>} versionContent={<p>Published version controls</p>} />); expect(html).toContain("Choose token image file"); expect(html).toContain("Recovery from the existing wallet"); expect(html).toContain("Published version controls"); expect(upload).not.toHaveBeenCalled(); });
  it("shows the bound future beneficiary and refund time in a funded request review", async () => {
    const f = fixture(), base = await prepareModuleEngineOperation({ ...f, account: ACCOUNT, token: TOKEN }); if (base.kind !== "execute") throw new Error();
    const prepared = { ...base, operation: { ...base.operation, operationId: ENGINE_OPERATIONS.request, data: encodeAbiParameters(parseAbiParameters("address,uint256,bytes32"), [addr(88), 2_000_000_000n, hash(81)]) } };
    const html = renderToStaticMarkup(<ModuleEngineTransactionReview prepared={prepared} busy={false} onConfirm={vi.fn()} onEdit={vi.fn()} quoteAsset={QUOTE} quoteDecimals={6} />);
    expect(html).toContain("Beneficiary wallet"); expect(html).toContain(addr(88)); expect(html).toContain("2033-05-18 03:33:20 UTC"); expect(html).toContain("5 quote tokens"); expect(html).toContain(hash(81));
    const malformed = renderToStaticMarkup(<ModuleEngineTransactionReview prepared={{ ...prepared, operation: { ...prepared.operation, data: "0x12" } }} busy={false} onConfirm={vi.fn()} onEdit={vi.fn()} />); expect(malformed).toContain("action details could not be read"); expect(malformed).toMatch(/disabled="">Confirm in wallet/);
  });
  it("keeps arbitrary contract timestamps readable without crashing Date rendering", () => { expect(moduleEngineUtcTimestamp(0n)).toBe("1970-01-01 00:00:00 UTC"); expect(moduleEngineUtcTimestamp((1n << 256n) - 1n)).toMatch(/^Unix time \d+ \(UTC\)$/); });
});
