import { describe, expect, it, vi } from "vitest";
import { decodeFunctionData, encodeAbiParameters, encodeEventTopics, encodeFunctionResult, erc20Abi, type Hex, type TransactionReceipt } from "viem";
import { moduleEngineLedgerAbi } from "@/lib/module-engine/abi";
import { computeModuleEngineHostManifestHash } from "@/lib/module-engine/catalog";
import { ENGINE_OPERATIONS, moduleEngineSettlementPaymentIntent, moduleEngineWithdrawalIntent, prepareModuleEngineApproval, prepareModuleEngineClaim, readModuleEngineAdministration, revalidateModuleEngineTransaction, verifyModuleEngineClaimReceipt } from "@/lib/module-engine/client";
import { fixture, ACCOUNT, TOKEN, QUOTE, addr, hash } from "./module-engine-fixture";

describe("contract derived engine administration and ETH claims", () => {
  it("uses launchId as the ledger accounting key and reads actual wallet balances", async () => { const f = fixture(); const state = await readModuleEngineAdministration({ ...f, account: ACCOUNT, token: TOKEN }); expect(state.fees.claimable).toBe(9n); expect(state.fees.claimed).toBe(4n); expect(state.fees.contributionByLaunch).toBe(2n); expect(state.escrow?.credit).toBe(1000n); });
  it("prepares an exact ledger claim with no creator or author label authority", async () => { const f = fixture(); vi.mocked(f.client.call).mockResolvedValue({ data: encodeFunctionResult({ abi: moduleEngineLedgerAbi, functionName: "claimTo", result: 9n }) }); const prepared = await prepareModuleEngineClaim({ ...f, token: TOKEN, account: ACCOUNT, recipient: addr(86) }); expect(prepared.kind).toBe("claim"); expect(prepared.transaction.to).toBe(f.release.contracts.ledger.address); expect(prepared.transaction.value).toBe("0x0"); expect(prepared.minimumAmount).toBe(9n); expect(decodeFunctionData({ abi: moduleEngineLedgerAbi, data: prepared.transaction.data })).toMatchObject({ functionName: "claimTo", args: [addr(86)] }); f.state.claimable = 8n; await expect(revalidateModuleEngineTransaction(prepared, ACCOUNT)).rejects.toThrow("balance changed"); });
  it("rejects zero claims and binds approval only to the released host", async () => { const f = fixture(); f.state.claimable = 0n; await expect(prepareModuleEngineClaim({ ...f, token: TOKEN, account: ACCOUNT, recipient: ACCOUNT })).rejects.toThrow(); vi.mocked(f.client.call).mockResolvedValue({ data: encodeFunctionResult({ abi: erc20Abi, functionName: "approve", result: true }) }); const approval = await prepareModuleEngineApproval({ ...f, token: QUOTE, account: ACCOUNT, amount: 15n }); expect(decodeFunctionData({ abi: erc20Abi, data: approval.transaction.data })).toMatchObject({ functionName: "approve", args: [f.host, 15n] }); expect(approval.spender).toBe(f.host); });
  it("verifies the actual ledger claim event, recipient and accounting update", async () => { const f = fixture(); f.state.claimed = 13n; const args = { beneficiary: ACCOUNT, recipient: addr(86), caller: ACCOUNT, amount: 9n }; const receipt = { status: "success", transactionHash: hash(90), blockNumber: 100n, blockHash: f.blockHash, logs: [{ address: f.release.contracts.ledger.address, transactionHash: hash(90), blockNumber: 100n, blockHash: f.blockHash, removed: false, topics: encodeEventTopics({ abi: moduleEngineLedgerAbi, eventName: "FeesClaimed", args }), data: encodeAbiParameters([{ type: "uint256" }], [9n]) }] } as unknown as TransactionReceipt; const input = { ...f, account: ACCOUNT, recipient: addr(86), minimumAmount: 9n, claimedBefore: 4n, receipt }; expect((await verifyModuleEngineClaimReceipt(input)).outputAmount).toBe(9n); await expect(verifyModuleEngineClaimReceipt({ ...input, recipient: ACCOUNT })).rejects.toThrow("recipient"); f.state.claimed = 12n; await expect(verifyModuleEngineClaimReceipt(input)).rejects.toThrow("not updated"); });
  it("derives fulfillment and refund timing from actual request parties", async () => {
    const f = fixture(), m = f.template.manifest.manifest; m.catalogDefinition.interface = "settlement-v1"; m.revision.operationPermissions = [{ operationId: ENGINE_OPERATIONS.request, inputRoles: 2, outputRoles: 0, authorization: 0 }, { operationId: ENGINE_OPERATIONS.fulfill, inputRoles: 0, outputRoles: 2, authorization: 1 }, { operationId: ENGINE_OPERATIONS.refund, inputRoles: 0, outputRoles: 2, authorization: 0 }]; f.template.manifestHash = computeModuleEngineHostManifestHash(f.template.manifest);
    const creator = await readModuleEngineAdministration({ ...f, token: TOKEN, account: ACCOUNT, requestId: hash(86) }); expect(creator.settlement?.canFulfill).toBe(true); expect(creator.settlement?.canRefund).toBe(false);
    const stranger = await readModuleEngineAdministration({ ...f, token: TOKEN, account: addr(85), requestId: hash(86) }); expect(stranger.settlement?.canFulfill).toBe(false); expect(stranger.settlement?.canRefund).toBe(false);
    f.state.timestamp += 601n; const payer = await readModuleEngineAdministration({ ...f, token: TOKEN, account: addr(89), requestId: hash(86) }).catch(error => error as Error);
    expect(payer).toBeInstanceOf(Error); // stale RPC time is fail-closed, never fabricated elapsed authority
    f.state.timestamp -= 601n; f.state.refundAfter = f.state.timestamp;
    const refund = await readModuleEngineAdministration({ ...f, token: TOKEN, account: addr(89), requestId: hash(86) }); expect(refund.settlement?.canRefund).toBe(true);
    const intent = moduleEngineSettlementPaymentIntent({ quoteAsset: QUOTE, request: refund.settlement!.request!, kind: "refund" }); expect(intent.recipient).toBe(addr(89)); expect(intent.minimumOutput).toBe(1000n); expect(intent.inputAmount).toBe(0n); expect(intent.data).toBe(encodeAbiParameters([{ type: "bytes32" }], [hash(86)]));
  });
  it("keeps withdrawal data and minimum output equal to the exact actor-funded amount", () => { const intent = moduleEngineWithdrawalIntent(QUOTE, ACCOUNT, 13n); expect(intent.minimumOutput).toBe(13n); expect(intent.data).toBe(encodeAbiParameters([{ type: "uint256" }], [13n])); expect(() => moduleEngineSettlementPaymentIntent({ quoteAsset: QUOTE, kind: "fulfill", request: { requestId: hash(80), payer: ACCOUNT, beneficiary: addr(85), amount: 2n, refundAfter: 12n, obligationHash: hash(81), status: 2 }, evidenceHash: hash(82) as Hex })).toThrow("closed"); });
});
