import { readFileSync } from "node:fs";
import Ajv2020 from "ajv/dist/2020";
import { describe, expect, it } from "vitest";

const read = (path: string) => JSON.parse(readFileSync(path, "utf8"));
const schema = read("public/schemas/custom-launch/guide/v1.json");
const document = read("public/openapi/launch-guide-v1.json");
// Generated by the real backend guide builder at profile4.1 with an activated seed adapter.
// Guidance-only synthetic runtime, never production or launch authorization evidence.
const example = read("tests/fixtures/robinhood-launch-guide-v1.json");
const validate = new Ajv2020({ strict: true, allErrors: true }).compile(schema);

describe("versioned public Robinhood launch guide contract", () => {
  it("documents an unauthenticated read and preserves the same response schema", () => {
    const { $schema, $id, ...component } = schema;
    expect($schema).toBe("https://json-schema.org/draft/2020-12/schema");
    expect($id).toBe("https://programmable.market/schemas/custom-launch/guide/v1.json");
    expect(document.components.schemas.RobinhoodLaunchGuideV1).toEqual(component);
    expect(Object.keys(document.paths)).toEqual(["/v4/chains/4663/launch-guide"]);
    const route = document.paths["/v4/chains/4663/launch-guide"];
    expect(Object.keys(route)).toEqual(["get"]);
    expect(route.get.security).toEqual([]);
    expect(route.get).not.toHaveProperty("requestBody");
    expect(route.get.responses["200"].content["application/json"].schema.$ref)
      .toBe("#/components/schemas/RobinhoodLaunchGuideV1");
  });

  it("accepts real builder output and rejects any claimed guide authorization", () => {
    expect(validate(example), JSON.stringify(validate.errors)).toBe(true);
    for (const field of ["requestEvaluated", "requestAuthorized", "permitIssued", "walletSignatureProduced"]) {
      const altered = structuredClone(example);
      altered.authority[field] = true;
      expect(validate(altered), field).toBe(false);
    }
    const scenario = structuredClone(example);
    scenario.scenarios[0].requestAuthorized = true;
    expect(validate(scenario)).toBe(false);
  });

  it("rejects unknown contracts, invented profiles and unbounded instructions", () => {
    const extra = structuredClone(example);
    extra.callerProof = "accepted";
    expect(validate(extra)).toBe(false);
    const profile = structuredClone(example);
    profile.profile.profileVersion = "4.2.0";
    expect(validate(profile)).toBe(false);
    const retry = structuredClone(example);
    retry.errorRecovery[0].retry = "change-key-and-retry";
    expect(validate(retry)).toBe(false);
    const oversized = structuredClone(example);
    oversized.scenarios[0].nextStep = "x".repeat(100_000);
    expect(validate(oversized)).toBe(false);
  });
});
