import { readFileSync } from "node:fs";
import Ajv2020 from "ajv/dist/2020";
import { describe, expect, it } from "vitest";

const read = (path: string) => JSON.parse(readFileSync(path, "utf8"));
const schema = read("public/schemas/custom-launch/guide/v1.json");
const document = read("public/openapi/launch-guide-v1.json");
// Generated by the real backend guide builder at profile4.1 with an activated seed adapter.
// Guidance-only synthetic runtime, never production or launch authorization evidence.
const example = read("tests/fixtures/robinhood-launch-guide-v1.json");
const validate = new Ajv2020({ strict: true, allErrors: true }).compile(schema);

describe("versioned public Robinhood launch guide contract", () => {
  it("documents an unauthenticated read and preserves the same response schema", () => {
    const { $schema, $id, ...component } = schema;
    expect($schema).toBe("https://json-schema.org/draft/2020-12/schema");
    expect($id).toBe("https://programmable.market/schemas/custom-launch/guide/v1.json");
    expect(document.components.schemas.RobinhoodLaunchGuideV1).toEqual(component);
    expect(Object.keys(document.paths)).toEqual(["/v4/chains/4663/launch-guide"]);
    const route = document.paths["/v4/chains/4663/launch-guide"];
    expect(Object.keys(route)).toEqual(["get"]);
    expect(route.get.security).toEqual([]);
    expect(route.get).not.toHaveProperty("requestBody");
    expect(route.get.responses["200"].content["application/json"].schema.$ref)
      .toBe("#/components/schemas/RobinhoodLaunchGuideV1");
  });

  it("accepts real builder output and rejects any claimed guide authorization", () => {
    expect(validate(example), JSON.stringify(validate.errors)).toBe(true);
    for (const field of ["requestEvaluated", "requestAuthorized", "permitIssued", "walletSignatureProduced"]) {
      const altered = structuredClone(example);
      altered.authority[field] = true;
      expect(validate(altered), field).toBe(false);
    }
    const scenario = structuredClone(example);
    scenario.scenarios[0].requestAuthorized = true;
    expect(validate(scenario)).toBe(false);
  });

  it("rejects unknown contracts, invented profiles and unbounded instructions", () => {
    const extra = structuredClone(example);
    extra.callerProof = "accepted";
    expect(validate(extra)).toBe(false);
    const profile = structuredClone(example);
    profile.profile.profileVersion = "4.2.0";
    expect(validate(profile)).toBe(false);
    const retry = structuredClone(example);
    retry.errorRecovery[0].retry = "change-key-and-retry";
    expect(validate(retry)).toBe(false);
    const oversized = structuredClone(example);
    oversized.scenarios[0].nextStep = "x".repeat(100_000);
    expect(validate(oversized)).toBe(false);
  });

  it("rejects known values attached to the wrong workflow, scenario or recovery row", () => {
    const workflow = structuredClone(example);
    workflow.workflow.find((step: { id: string }) => step.id === "check-concept").requiredScope = "custom-launch:create";
    expect(validate(workflow)).toBe(false);
    const scenario = structuredClone(example);
    const combined = scenario.scenarios.find((row: { id: string }) => row.id === "combined-token-hook");
    combined.assessment = example.scenarios[0].assessment;
    combined.reason = example.scenarios[0].reason;
    combined.nextStep = example.scenarios[0].nextStep;
    expect(validate(scenario)).toBe(false);
    const recovery = structuredClone(example);
    recovery.errorRecovery[0].instruction = example.errorRecovery[1].instruction;
    expect(validate(recovery)).toBe(false);
    const duplicates = structuredClone(example);
    duplicates.scenarios[1] = structuredClone(duplicates.scenarios[0]);
    expect(validate(duplicates)).toBe(false);
  });

  it("binds every scenario assessment to the selected profile", () => {
    for (const profile of schema.properties.profile.enum.filter((value: { profileVersion?: string } | null) => value?.profileVersion !== "4.1.0")) {
      const changed = structuredClone(example);
      changed.profile = profile;
      expect(validate(changed)).toBe(false);
      changed.scenarios = structuredClone(schema.allOf[0].else.properties.scenarios.const);
      expect(validate(changed), JSON.stringify(validate.errors)).toBe(true);
    }
  });
});
