export const developerDocsPath = "/docs/developers";
export const developerDocsMarkdownPath = "/docs/developers.md";

const canonicalDeveloperOrigin = "https://developers.programmable.family";

export const developerDocsMarkdown = [
  "# Programmable trading terminal integration",
  "",
  "> Public read-only specification for detecting Programmable launches and assigning the two supported terminal labels.",
  "",
  "Canonical guide: https://programmable.family/docs/developers",
  `API base: ${canonicalDeveloperOrigin}/api/v1`,
  `Discovery: ${canonicalDeveloperOrigin}/.well-known/programmable.json`,
  `Live manifest: ${canonicalDeveloperOrigin}/api/v1/manifest`,
  `OpenAPI 3.1: ${canonicalDeveloperOrigin}/openapi/programmable-v1.yaml`,
  "Authentication: none",
  "Network: Ethereum mainnet",
  "",
  "## Required labels",
  "",
  "| API category | Terminal label | Current boundary |",
  "| --- | --- | --- |",
  "| `classic` | `Programmable Classic` | Current and historical Classic releases |",
  "| `custom` | `Programmable Custom` | Listed first-party Custom launches today and future registered Custom hooks |",
  "",
  "Existing first-party Stock Paired launches are live as `custom`. Public Custom submission and the open Custom Registry are prelaunch. A future Custom hook enters the feed only after recognized onchain launch evidence exists.",
  "",
  "## Choose an integration path",
  "",
  "- **Terminals and scanners:** Detect launches, apply the two labels and expose only verified market capabilities.",
  "- **Launch providers:** Connect an external template factory to the future Programmable Custom Registry.",
  "- **Data platforms and bots:** Backfill, deduplicate and poll the read-only feed.",
  "- **AI agents:** Read this Markdown, the OpenAPI document, JSON Schemas and the provider guide.",
  "",
  "## Minimal terminal consumer",
  "",
  "```ts",
  `const response = await fetch("${canonicalDeveloperOrigin}/api/v1/launches?limit=100")`,
  "if (!response.ok) throw new Error(`Programmable API returned ${response.status}`)",
  "",
  "const feed = await response.json()",
  "const rows = feed.items.map((launch) => ({",
  "  id: launch.launchId,",
  "  chainId: launch.chainId,",
  "  tokenAddress: launch.token.address,",
  '  label: launch.category === "classic"',
  '    ? "Programmable Classic"',
  '    : "Programmable Custom",',
  "  finality: launch.launch.finality,",
  "  markets: launch.markets,",
  "}))",
  "```",
  "",
  "Use `category=classic` or `category=custom` to request one label directly.",
  "",
  "## Current Ethereum sources",
  "",
  "Resolve these values from the live manifest in production code.",
  "",
  "| Release | Label | Launcher | Hook | Event | Topic 0 | From block |",
  "| --- | --- | --- | --- | --- | --- | --- |",
  "| Classic V3 | Programmable Classic | `0xC3bd04aAc2fb2ba58efD7Eb673E544E0B80De770` | `0x35Fe236EA82F7cF525c9719d7df8F49F94D720CC` | `MemeTokenLaunchedV2` | `0xf23bd7fdf96caf9195ba5982de473632f59015abc714915dfbbe06cbd8e255e5` | `25639596` |",
  "| Stock Paired V3 | Programmable Custom | `0x0573879f72d8eE8B0e5a4Ec5E8bcDb2fCab9E51c` | `0x90c67C1E866f86526F0e338459cD435E1F23A0cc` | `StockPairedTokenLaunched` | `0xe33bd69b6e794281bc106d622fbe0c587aeabf86d1ca4d1afcd583cf8a3e8935` | `25642745` |",
  "",
  "A complete historical backfill must also include Classic V1, Classic V2, Stock Paired V1 and Stock Paired V2 from the manifest. Classic V2 uses fee hook `0x025a386eAa79f6067d29848FD05ccC71bEAb20CC`; new Classic launches use the V3 hook above.",
  "",
  "## Launch provider integration",
  "",
  "Status: **prelaunch specification**. The open Custom Registry is not deployed. No live registry address or transaction instruction is published.",
  "",
  "External providers such as Basebit keep their own factories and templates. Accepted partner launches use the same public `custom` category and `Programmable Custom` label. Provider attribution remains separate metadata and never creates a third category.",
  "",
  "### Supported registration modes",
  "",
  "1. **Atomic Programmable adapter:** An approved adapter calls the provider factory, validates the returned token, hook and market, then registers the launch before the transaction completes.",
  "2. **Verified factory callback:** An allowlisted provider factory calls the registry from inside its launch transaction. The registry binds the factory and runtime code to one provider ID.",
  "",
  "A frontend request, API response, webhook or later metadata submission is not canonical provenance. Registration must be authenticated and atomic with the provider launch.",
  "",
  "### Provider handoff package",
  "",
  "- Provider ID, supported chains, factory and template-registry addresses.",
  "- Verified source, ABI, deployment transaction, start block and runtime code hashes.",
  "- Stable template ID, version, configuration hash and upgrade authority.",
  "- Receipt mapping for token, hook, pool or market, creator and external launch ID.",
  "- PoolManager, hook permission flags, router assumptions, mutable roles and external calls.",
  "- Creator and protocol fees, recipients, caps and charge basis.",
  "- Discovery, chart, quote, simulation and execution support as separate capabilities.",
  "- Audit scope, tests, mainnet example, negative cases and incident contact.",
  "",
  "### Draft registry event",
  "",
  "```solidity",
  "event ProgrammableCustomLaunchRegistered(",
  "  bytes32 indexed launchId,",
  "  bytes32 indexed providerId,",
  "  address indexed token,",
  "  address factory,",
  "  address hook,",
  "  bytes32 marketId,",
  "  bytes32 templateId,",
  "  bytes32 templateVersion,",
  "  bytes32 configurationHash,",
  "  address creator",
  ");",
  "```",
  "",
  "One launch ID and token registration are accepted per chain. Provider and factory authorization, template review, market support and audit evidence remain separate facts. Suspending a provider blocks future registrations but does not rewrite historical provenance.",
  "",
  "## Required fields",
  "",
  "- `category`: public label mapping.",
  "- `chainId + token.address`: canonical asset key.",
  "- `launchId`: replay-safe launch identity.",
  "- `launch.finality`: observed, confirmed, finalized or orphaned.",
  "- `verification`: source deployment and provenance evidence.",
  "- `markets[].support`: separate chart, quote, simulation and execution gates.",
  "- `fees`: verified rate and charge mode. Never infer fees from category.",
  "- `extensions`: namespaced additive data. Unknown values are not instructions.",
  "",
  "## Verification rules",
  "",
  "A Programmable label means that the asset traces to a recognized source deployment. It is not a guarantee of price, liquidity, metadata truth or the absence of every economic risk. The v1 schema intentionally has no universal `safe` or `audited` boolean.",
  "",
  "Current Classic V3 release evidence establishes a fixed supply of 1,000,000,000 tokens, no owner mint, blacklist, pause or ERC20 transfer tax, permanently held one-sided Uniswap v4 liquidity, immutable directional fees and a recorded mainnet buy, sell and claim lifecycle. A terminal should still perform its normal pool state, liquidity, quote and simulation checks before enabling execution.",
  "",
  "Custom is a launch family, not one mechanic. Preserve provenance, capabilities, markets, fee disclosure and any specific audit evidence independently. Do not infer an audit from `category=custom`.",
  "",
  "## Backfill and live updates",
  "",
  "1. Fetch `/.well-known/programmable.json`, `/api/v1/status` and `/api/v1/manifest`.",
  "2. Traverse `/api/v1/launches` with `page.nextCursor` while `page.hasMore` is true.",
  "3. Apply every page idempotently and persist `page.resumeCursor` only after the traversal is durable.",
  "4. Start the next poll with `after={resumeCursor}`.",
  "5. Deduplicate by `launchId` and reconcile finality and orphaned records.",
  "",
  "Cursors are opaque. Store and return them unchanged.",
  "",
  "## Market data and execution",
  "",
  "The launch feed is read-only. It does not fabricate prices, volume or transaction payloads. Keep a recognized launch visible when `markets` is empty. Enable chart, quote, simulation or execution only when the corresponding market support field and a separately verified adapter allow it.",
  "",
  "## API routes",
  "",
  `- [Status](${canonicalDeveloperOrigin}/api/v1/status)`,
  `- [Manifest](${canonicalDeveloperOrigin}/api/v1/manifest)`,
  `- [Launch feed](${canonicalDeveloperOrigin}/api/v1/launches)`,
  `- [Token detail example](${canonicalDeveloperOrigin}/api/v1/launches/1/0x56a96463ead0c0b9b4e4df9e41805bb8877074a6)`,
  `- [Token list](${canonicalDeveloperOrigin}/api/v1/token-list)`,
  "",
  "The detail path requires both `{chainId}` and `{tokenAddress}`. `/token` alone is not an API route.",
  "",
  "## Normative resources",
  "",
  `- [OpenAPI 3.1](${canonicalDeveloperOrigin}/openapi/programmable-v1.yaml)`,
  "- [JSON Schemas](https://github.com/0xprogrammable/developers/tree/main/schemas/v1)",
  "- [Ethereum ABIs](https://github.com/0xprogrammable/developers/tree/main/abis/ethereum)",
  "- [Terminal guide](https://github.com/0xprogrammable/developers/blob/main/docs/guides/terminals-and-scanners.md)",
  "- [Launch provider guide](https://github.com/0xprogrammable/developers/blob/main/docs/guides/launch-providers.md)",
  "- [Fixtures](https://github.com/0xprogrammable/developers/tree/main/fixtures/v1)",
  "- [Integration support](https://github.com/0xprogrammable/developers/issues)",
].join("\n");

export const programmableLlmsIndex = [
  "# Programmable",
  "",
  "> Public integration sources for Programmable Classic and Custom launches on Ethereum.",
  "",
  "Canonical product: https://programmable.family",
  `Developer API: ${canonicalDeveloperOrigin}`,
  "Source: https://github.com/0xprogrammable",
  "",
  "## Integration sources",
  "",
  "- [Trading terminal guide](https://programmable.family/docs/developers.md): Labels, contracts, events, required fields and ingestion rules.",
  "- [Launch provider guide](https://github.com/0xprogrammable/developers/blob/main/docs/guides/launch-providers.md): Prelaunch partner factory and registry requirements.",
  "- [Full agent context](https://programmable.family/llms-full.txt): Complete current integration context.",
  `- [Discovery document](${canonicalDeveloperOrigin}/.well-known/programmable.json): Stable machine-readable entry point.`,
  `- [OpenAPI 3.1](${canonicalDeveloperOrigin}/openapi/programmable-v1.yaml): Normative HTTP contract.`,
  "- [JSON Schemas](https://github.com/0xprogrammable/developers/tree/main/schemas/v1): Normative response schemas.",
  "- [Developer repository](https://github.com/0xprogrammable/developers): Guides, ABIs, fixtures, examples and conformance tests.",
  "",
  "## Current boundary",
  "",
  "- Map `classic` to `Programmable Classic`.",
  "- Map `custom` to `Programmable Custom`.",
  "- Existing first-party Stock Paired records are live as Custom.",
  "- Public Custom submission and the open Custom Registry are prelaunch.",
  "- The v1 API is public, read-only and requires no API key.",
  "- Category is not a universal audit or safety flag.",
  "- Chart, quote, simulation and execution support must be checked per market.",
].join("\n");

export const programmableLlmsFullFallback = [
  programmableLlmsIndex,
  "",
  "## Complete integration guide",
  "",
  developerDocsMarkdown,
  "",
  "Canonical full context:",
  `${canonicalDeveloperOrigin}/llms-full.txt`,
].join("\n");
