export const developerDocsPath = "/docs/developers";
export const developerDocsMarkdownPath = "/docs/developers.md";

const canonicalDeveloperOrigin = "https://developers.programmable.family";

export const developerDocsMarkdown = [
  "# Programmable developer integrations",
  "",
  "> Add Programmable launches to a terminal, scanner, wallet, indexer, app, or AI agent through one public read-only API.",
  "",
  "Canonical page: https://programmable.family/docs/developers",
  `Developer portal: ${canonicalDeveloperOrigin}`,
  `API base: ${canonicalDeveloperOrigin}/api/v1`,
  `Discovery: ${canonicalDeveloperOrigin}/.well-known/programmable.json`,
  `OpenAPI: ${canonicalDeveloperOrigin}/openapi/programmable-v1.yaml`,
  "Authentication: none for public read-only endpoints",
  "Network: Ethereum mainnet",
  "",
  "## Five-minute integration",
  "",
  "1. Fetch `/.well-known/programmable.json` and follow its URLs instead of hard-coding deployment addresses.",
  "2. Check `/api/v1/status`, then fetch `/api/v1/manifest` and `/api/v1/launches`.",
  "3. Continue the current traversal with `page.nextCursor` while `page.hasMore` is true.",
  "4. Persist `page.resumeCursor` only after every page is durably applied, then pass it as `after` for the next incremental poll.",
  "5. Key assets by `chainId + token.address`, deduplicate launches by `launchId`, and preserve finality and provenance.",
  "",
  "```bash",
  `curl -fsSL '${canonicalDeveloperOrigin}/api/v1/launches?limit=50'`,
  "```",
  "",
  "Fetch one launch with both identity values:",
  "",
  "```bash",
  `curl -fsSL '${canonicalDeveloperOrigin}/api/v1/launches/1/0x56a96463ead0c0b9b4e4df9e41805bb8877074a6'`,
  "```",
  "",
  "`/token` alone is not an API route. The detail path requires `{chainId}` and `{tokenAddress}`.",
  "",
  "## Response shape",
  "",
  "A launch feed contains `schemaVersion`, `status`, `snapshot`, `items`, and `page`. Each item contains `launchId`, `category`, `chainId`, `token`, `launch`, `verification`, `capabilities`, `markets`, `fees`, and `extensions`.",
  "",
  "`category` is exactly `classic | custom`. A valid launch can have zero, one, or several markets. Never invent a pool, price, volume, chart, quote, or execution route when support is absent.",
  "",
  "## Production rules",
  "",
  "- The API is read-only. It returns no transaction payloads and authorizes no execution.",
  "- Use the manifest for current deployments. Do not hard-code one launcher or registry as the full source.",
  "- Preserve null, unavailable, partial, degraded, observed, confirmed, finalized, and orphaned states exactly.",
  "- Treat creator names, symbols, images, descriptions, and links as untrusted display metadata.",
  "- Ignore unknown optional fields while keeping unknown launches visible and unsupported actions disabled.",
  "- Honor `Cache-Control`, `ETag`, `Retry-After`, and the problem response schema.",
  "",
  "## Product-specific guides",
  "",
  "- [Terminals and scanners](https://github.com/0xprogrammable/developers/blob/main/docs/guides/terminals-and-scanners.md)",
  "- [Indexers and data platforms](https://github.com/0xprogrammable/developers/blob/main/docs/guides/indexers.md)",
  "- [Wallets and explorers](https://github.com/0xprogrammable/developers/blob/main/docs/guides/wallets.md)",
  "- [Bots, apps and games](https://github.com/0xprogrammable/developers/blob/main/docs/guides/apps-and-games.md)",
  "",
  "## Current capability boundary",
  "",
  "The public v1 API provides launch discovery, identity, provenance, finality, market declarations, fee disclosure, cursors, schemas, and a compatibility token list. Price candles, normalized volume, quotes, simulation, and transaction execution require a separately verified market adapter and must remain disabled when support is unavailable. Open community Custom intake remains prelaunch.",
  "",
  "## AI-agent entry points",
  "",
  "- Index: https://programmable.family/llms.txt",
  "- Full integration context: https://programmable.family/llms-full.txt",
  "- This page as Markdown: https://programmable.family/docs/developers.md",
  `- Canonical developer context: ${canonicalDeveloperOrigin}/llms-full.txt`,
  "- OpenAPI 3.1: https://developers.programmable.family/openapi/programmable-v1.yaml",
  "",
  "## Reference",
  "",
  `- [Live status](${canonicalDeveloperOrigin}/api/v1/status)`,
  `- [Deployment manifest](${canonicalDeveloperOrigin}/api/v1/manifest)`,
  `- [Launch feed](${canonicalDeveloperOrigin}/api/v1/launches)`,
  `- [Live token-detail example](${canonicalDeveloperOrigin}/api/v1/launches/1/0x56a96463ead0c0b9b4e4df9e41805bb8877074a6)`,
  `- [Token list](${canonicalDeveloperOrigin}/api/v1/token-list)`,
  "- [JSON Schemas](https://github.com/0xprogrammable/developers/tree/main/schemas/v1)",
  "- [Developer repository](https://github.com/0xprogrammable/developers)",
].join("\n");

export const programmableLlmsIndex = [
  "# Programmable",
  "",
  "> Programmable is an Ethereum launch platform. This index points humans and AI agents to the current public product and developer integration contracts.",
  "",
  "Canonical product: https://programmable.family",
  `Developer API: ${canonicalDeveloperOrigin}`,
  "Source: https://github.com/0xprogrammable",
  "",
  "## Developer integration",
  "",
  "- [Developer overview](https://programmable.family/docs/developers.md): Concise human and agent-readable integration guide.",
  "- [Full agent context](https://programmable.family/llms-full.txt): Complete current developer contract.",
  `- [Discovery document](${canonicalDeveloperOrigin}/.well-known/programmable.json): Stable machine-readable entry point.`,
  `- [OpenAPI 3.1](${canonicalDeveloperOrigin}/openapi/programmable-v1.yaml): Normative HTTP contract.`,
  "- [JSON Schemas](https://github.com/0xprogrammable/developers/tree/main/schemas/v1): Normative response schemas.",
  "- [Developer repository](https://github.com/0xprogrammable/developers): Guides, fixtures, examples, schemas, and conformance tests.",
  "",
  "## Current boundaries",
  "",
  "- Classic launch discovery is live on Ethereum.",
  "- Existing first-party stock-paired records normalize as `custom`.",
  "- Open Custom intake and the open Custom Registry are prelaunch.",
  "- The v1 API is public, read-only, and requires no API key.",
  "- Charting, quote, simulation, and execution support are explicit per market and must never be guessed.",
].join("\n");

export const programmableLlmsFullFallback = [
  programmableLlmsIndex,
  "",
  "## Integration guide",
  "",
  developerDocsMarkdown,
  "",
  "The canonical full developer context is available at:",
  `${canonicalDeveloperOrigin}/llms-full.txt`,
].join("\n");
