import {
  LAUNCH_KIND_V1,
  PROGRAMMABLE_LAUNCH_STAMP_MANIFEST,
  PROGRAMMABLE_LAUNCH_STAMP_RESOURCES,
  PROGRAMMABLE_LAUNCH_STAMP_ROUTER_V1_ABI,
} from "@/components/launch-stamp-docs-contract";
import {
  PROGRAMMABLE_PUBLIC_REPOSITORIES,
  V4_TOKEN_ADDRESS,
} from "@/components/docs-public-policy";

export const developerDocsPath = "/docs/developers";
export const developerDocsMarkdownPath = "/docs/developers.md";
const customLaunchApiOrigin = "https://api.programmable.market";
const apiKeysUrl = "https://programmable.market/developers/api-keys";
const customLaunchApiOpenApiUrl =
  "https://programmable.market/openapi/custom-launch-v1.json";
const customLaunchApiGuideUrl =
  "https://programmable.market/developers/custom-launch-api-v1.md";

const manifest = PROGRAMMABLE_LAUNCH_STAMP_MANIFEST;
const router = manifest.launchStampRouter;
const canary = router.canaryEvidence;
const resources = PROGRAMMABLE_LAUNCH_STAMP_RESOURCES;
const abi = PROGRAMMABLE_LAUNCH_STAMP_ROUTER_V1_ABI;

const launchKindRows = LAUNCH_KIND_V1.filter(
  (kind) => kind.publicLabel !== null,
).map(
  (kind) => `| \`${kind.value}\` | \`${kind.name}\` | ${kind.publicLabel} |`,
);

const eventRows = Object.values(router.events).map(
  (event) =>
    `| \`${event.name}\` | \`${event.signature}\` | \`${event.topic0}\` |`,
);

export function buildDeveloperDocsMarkdown(): string {
  return [
    "# Programmable developer APIs",
    "",
    "> API-key Custom launch preparation plus read-only verification of Router-stamped Programmable provenance on Ethereum.",
    "",
    `Custom Launch API: ${customLaunchApiOrigin}`,
    `Create and revoke API keys: ${apiKeysUrl}`,
    `Custom Launch API OpenAPI: ${customLaunchApiOpenApiUrl}`,
    `Custom Launch API guide: ${customLaunchApiGuideUrl}`,
    `Deployment manifest: ${resources.manifestUrl}`,
    `Frozen Router ABI: ${resources.abiUrl}`,
    `ABI SHA-256: ${resources.abiSha256}`,
    `GitHub reference: ${resources.referenceUrl}`,
    "Programmable read endpoints: no authentication",
    "Custom Launch API: wallet-bound pm_live_ API key",
    "Ethereum RPC authentication: provider-specific",
    "",
    "## API-first Custom launches",
    "",
    `Connect a wallet and create a key at ${apiKeysUrl}. Copy the \`pm_live_\` secret when it is shown; list responses never return it again. Give the key only to the agent that should prepare launches for that wallet.`,
    "",
    "V1 keys receive exactly `custom-launch:create` and `custom-launch:read`. `fees:claim` and `buybacks:manage` are reserved and disabled. Future endpoints and scopes are additive, and existing keys never inherit a newly enabled scope.",
    "",
    "Keys expire after 90 days by default, may be issued for at most 366 days, and are limited to 10 active keys per wallet.",
    "",
    "An API key is not a wallet or private key. The platform validates the submitted manifest digest, graph constraints, required agent attestation and evidence digests, and exact permit binding, then returns the prepared Router action. It does not compile source, simulate the transaction, audit the project, or attest safety. A controller wallet, or an agent separately authorized to use that wallet, must review, sign, and broadcast the action. The API key alone never grants wallet signing authority.",
    "",
    "### Create a launch",
    "",
    "Send one closed JSON request to `POST /v1/custom-launches`. Use the same `Idempotency-Key` and identical body to resolve an ambiguous timeout without creating duplicate work.",
    "",
    "```sh",
    `curl --fail-with-body ${customLaunchApiOrigin}/v1/custom-launches` + " \\",
    "  --request POST \\",
    "  --header \"Authorization: Bearer $PROGRAMMABLE_API_KEY\" \\",
    "  --header \"Content-Type: application/json\" \\",
    "  --header \"Idempotency-Key: agent-launch-2026-0001\" \\",
    "  --data-binary @launch.json",
    "```",
    "",
    "`Idempotency-Key` is 16 to 128 characters from `[A-Za-z0-9._:-]`. A new request returns `202`; an exact replay may return `200`. Reusing the key with a different body or reusing a conflicting wallet nonce returns `409`.",
    "",
    "New reservations are limited to 30 per rolling hour and 100 per rolling day for the wallet principal and route. Exact idempotent replays bypass quota. A `429 LAUNCH_QUOTA_EXCEEDED` response includes `limit`, `windowSeconds`, and `retryAfterSeconds`, plus the same delay in the `Retry-After` header.",
    "",
    "If a durable prepared permit expires before platform signing, the request becomes terminal `failed` with `failure.code: PERMIT_EXPIRED` and `failure.retryable: false`. Submit a new request with a new nonce and Idempotency-Key.",
    "",
    "### Closed request body",
    "",
    "The top-level object has no unknown fields, is limited to 2 MiB and requires all eight fields:",
    "",
    "- `schemaVersion`: exactly `programmable.custom-launch-create-request.v1`",
    "- `launchWallet`: the Ethereum address bound to the API key",
    "- `chainId`: the string `1`",
    "- `nonce`: one nonzero lowercase `bytes32`",
    "- `sourceDescriptor`: one `DeterministicSourceBundleV2` descriptor",
    "- `sourceBundleManifest`: one complete, non-empty `SourceBundleManifestV2`",
    "- `graphBundle`: one executable `CustomGraphBundleV1`",
    "- `agentAttestation`: one `AgentLaunchAttestationV1` self-attestation with evidence digests",
    "",
    "`sourceDescriptor` requires exactly `schemaVersion: 2.0.0`, `kind: deterministic-source-bundle`, `controllerWallet`, `sourceLineageNonce`, `sourceBundleDigest`, `bundleContentSha256`, and `publicOriginCommitment`. `controllerWallet` must equal `launchWallet`. `graphBundle.sourceBundleSha256` must equal `sourceDescriptor.bundleContentSha256`.",
    "",
    "`sourceBundleManifest` contains exactly `schemaVersion: 2.0.0` and at least one entry. Entries are unique and strictly sorted by UTF-8 path bytes. Every entry contains exactly `path`, `kind`, `mode`, decimal `byteLength`, `contentSha256`, and `symlinkTarget`. Files use mode `100644` or `100755` with a null target; symlinks use mode `120000` with a string target. The platform recomputes the frozen manifest digest and requires it to match `sourceDescriptor.sourceBundleDigest`; it does not fetch or compile the source files.",
    "",
    "`graphBundle` contains exactly `schemaVersion: programmable.custom-graph-bundle.v1`, `sourceBundleSha256`, `targets`, and `pool`. It accepts 1 to 16 acyclic targets, exactly one `token` target and one `hook` target. Aggregate init code and initializer calldata are limited to 524,288 bytes.",
    "",
    "Every target contains exactly `targetId`, `applicantSalt`, `creationBytecode`, `constructorArguments`, `initializerCalldata`, `constructorAddressLocators`, `initializerAddressLocators`, `deploymentValueWei`, `initializerValueWei`, `expectedRuntimeCodeHash`, `componentKind`, and `declaredHookPermissions`. Each address locator contains exactly `targetId`, nonnegative `byteOffset`, and `encoding` (`abi-address-word` or `packed-address-20`). Non-hook targets use `declaredHookPermissions: null`; the hook uses a unique subset of the 14 Uniswap v4 permissions, and its predicted address bits must match that set.",
    "",
    `The pool contains exactly \`tokenTargetId\`, \`hookTargetId\`, \`fee\`, and \`tickSpacing\`. Target IDs must select the declared token and hook. The standalone Custom Launch API schema, including every bound, enum, and response, is published at ${customLaunchApiOpenApiUrl}.`,
    "",
    "The required agent attestation contains exactly `schemaVersion: programmable.agent-launch-attestation.v1`, `subjectGraphBundleHash`, `agentId`, canonical UTC `checkedAt`, and 1 to 64 unique checks. Each check contains `checkId` and a non-null `sha256:<64 lowercase hex>` evidence digest. It is the agent's self-attestation for the submitted graph subject, is excluded from platform permit authorization and is not a Programmable safety, audit, approval, compilation, or simulation claim.",
    "",
    "### List wallet launch requests",
    "",
    `Read \`${customLaunchApiOrigin}/v1/custom-launches?limit=10\` with \`custom-launch:read\`. The newest-first collection contains only requests owned by the key's wallet principal. \`limit\` defaults to 10 and is capped at 25; pass an unchanged non-null \`nextCursor\` as \`cursor\` for the next page. The collection is durable. For \`authorized\` or \`submitted\` rows in the requested page, list reads perform bounded best-effort chain reconciliation; RPC failure never hides durable history. Use the single-resource route for the full prepared artifact and exact output.`,
    "",
    "### Read launch state",
    "",
    `Read \`${customLaunchApiOrigin}/v1/custom-launches/{launchId}\` with the same Bearer key. The state is one of \`received\`, \`validating\`, \`prepared\`, \`authorized\`, \`submitted\`, \`finalized\`, \`failed\`, or \`cancelled\`.`,
    "",
    "The path keeps the legacy name `launchId`, but its value is the API request UUID. Every resource returns that UUID as both `launchId` and the explicit `requestId`. The separate `onchainLaunchId` is a bytes32 Router identifier; it is null before preparation and when a terminal failure clears the durable output.",
    "",
    "`prepared` means an exact artifact exists. `authorized` means the platform permit is attached and the wallet action is ready; it is still not wallet-signed or broadcast. Every response `requestHash` is a labeled `sha256:<64 lowercase hex>` digest. `submitted` means a canonical Router event and same-block `launchStamp` getter record match the prepared artifact but have fewer than 64 confirmations. `finalized` means the same evidence reached at least 64 confirmations.",
    "",
    "After the controller wallet broadcasts the exact transaction, poll the single-resource GET. That route is the precise full-output status path. POST only captures the bounded observation window; list reads perform bounded best-effort reconciliation for pending rows, and there is no background lifecycle reconciliation timer. After website discovery refreshes, a finalized launch is eligible to appear in Explore and the connected wallet's Profile without Registry publication. Third-party discovery and listing depend on each indexer implementing the published Router verification flow.",
    "",
    "The current website claim flow supports only explicitly verified fee models. A Router-stamped arbitrary Custom hook is not automatically claimable, and the `fees:claim` and `buybacks:manage` API operations are not active in V1.",
    "",
    "### Provenance boundary",
    "",
    "A successful Custom Launch API flow can establish that the finalized coin was launched through Programmable when the Router stamp verifies. The Router verifies fixed runtime, token, hook, PoolManager and pool bindings and requires an initialized pool with nonzero `sqrtPriceX96`. It does not prove active liquidity or tradability; the Custom graph owns its liquidity behavior.",
    "",
    "The source descriptor and agent attestation remain caller-declared offchain evidence. Programmable checks their shape, digests and graph binding but does not fetch or assess the evidence, prove that source produced bytecode or adopt the agent's claims. Router provenance does not establish approval, safety, audit coverage, liquidity, tradability, endorsement or future value.",
    "",
    "## Scope",
    "",
    "Only launches executed and stamped through this Router inside its published block range have Router V1 provenance. Launches before `startBlock`, and direct factory calls outside the Router even when later, do not.",
    "",
    "After bootstrap from the manifest and ABI, point verification requires only an Ethereum provider. A Programmable launch-feed API, indexer, Supabase project, or application server is not required. Continuous event indexing is optional.",
    "",
    "## Router binding",
    "",
    "| Field | Canonical value |",
    "| --- | --- |",
    `| \`status\` | \`${router.status}\` |`,
    `| \`chainId\` | \`${manifest.chainId}\` |`,
    `| \`address\` | \`${router.address}\` |`,
    `| \`startBlock\` | \`${router.startBlock}\` |`,
    `| \`endBlock\` | \`${router.endBlock ?? "null"}\` |`,
    `| \`runtimeCodeHash\` | \`${router.runtimeCodeHash}\` |`,
    `| \`abiSha256\` | \`${router.abiSha256}\` |`,
    `| \`finalityConfirmations\` | \`${router.finalityConfirmations}\` |`,
    "",
    "Read the stable discovery document, follow `manifestUrl`, then use `launchStampRouter` from the deployment manifest. Verify the downloaded ABI bytes against `abiSha256` before the first lookup. At the selected canonical block, also verify the Router runtime and immutable binding getters from the manifest.",
    "",
    "## Launch kinds",
    "",
    "Classify only from the returned stamp record. Names, tickers, logos, creator metadata, factory lookalikes, and shared hook addresses are not provenance.",
    "",
    "| Value | Enum | Public label |",
    "| --- | --- | --- |",
    ...launchKindRows,
    "",
    "`LaunchKindV1.Invalid = 0` is never a Programmable launch classification.",
    "",
    "## Point verification",
    "",
    "Resolve one finalized canonical block. Use that block for every runtime, binding, lookup, record, and proof read.",
    "",
    "Remote RPC URLs must use HTTPS. Plain HTTP is accepted only for loopback development endpoints.",
    "",
    "### Canonical preflight",
    "",
    "1. Fetch the official discovery document and manifest. Require `status: live`, or `retired` for a historical read inside the published block range.",
    "2. Require the complete manifest activation data: finalized canary evidence, chain and Router binding, all six immutable binding fields, block range, finality policy, runtime and ABI hashes, the sole payable atomic signature and selector, every getter descriptor, and every event topic and indexed layout.",
    "3. Resolve the chosen block to one concrete number and opening hash. Enforce `startBlock`, `endBlock` when present, and the published confirmation policy for explicit block-number reads.",
    "4. Require `eth_chainId == manifest.chainId`. At the same block, require the Router runtime Keccak-256 and the exact downloaded ABI byte SHA-256 to match the manifest. Derive and validate every advertised getter selector, event topic, indexed layout, and the sole payable atomic selector from that ABI.",
    "5. Call `CHAIN_ID()` and all six immutable address/runtime binding getters. Require exact manifest matches, then verify `eth_getCode` runtime hashes for the permit authority, Graph Factory, and PoolManager.",
    "",
    "### Resolve the launch ID",
    "",
    "### Token",
    "",
    `1. Call \`${abi.primaryReads[0].signature}\`.`,
    "2. A successful zero result is a `NOT_STAMPED` candidate. Complete any required closing canonical-block check before returning it.",
    "",
    "### Uniswap v4 pool",
    "",
    `1. Call \`${abi.primaryReads[1].signature}\` with \`(PoolManager, poolId)\`.`,
    "2. A successful zero result is a `NOT_STAMPED` candidate. Complete any required closing canonical-block check before returning it.",
    "",
    "### Exclusive component",
    "",
    `1. Call \`${abi.componentReads[1].signature}\`. Use this path only for a component explicitly exclusive to one launch.`,
    "2. The shared Classic hook is not a launch identifier.",
    "3. A successful zero result is a `NOT_STAMPED` candidate. Complete any required closing canonical-block check before returning it.",
    "",
    "### Validate a nonzero result",
    "",
    `1. Call \`${abi.primaryReads[2].signature}\` with the nonzero launch ID and require a supported nonzero \`record.kind\`.`,
    "2. Require valid address encoding for `launchWallet`, `token`, `hook`, `poolManager`, and `routeLauncher`. Require nonzero `poolId`, `poolKeyHash`, `componentSetHash`, `routePayloadHash`, `routeLauncherRuntimeCodeHash`, `expectedResultHash`, `permitDigest`, and `stampHash`.",
    "3. Require exact queried identity: `record.token == token`, or exact equality with `record.poolManager` and `record.poolId`. The record PoolManager must also equal the immutable manifest binding.",
    `4. For a token or exclusive component, call \`${abi.componentReads[0].signature}\` and require the same launch ID and \`record.stampHash\`. Require a nonzero recorded \`${abi.componentReads[2].signature}\`.`,
    "5. For `CustomGraph`, require `record.routeLauncher` and `record.routeLauncherRuntimeCodeHash` to match the immutable Graph Factory binding. For `Classic`, retain the permit-bound launcher and runtime recorded in the stamp; do not invent a Classic immutable.",
    "6. A current component-runtime comparison is a separate drift signal. A mismatch does not change the historical Router-provenance result.",
    "7. Prefer EIP-1898 `{ blockHash, requireCanonical: true }` reads. If the provider requires number-bound reads, refetch that height and require its closing hash to equal the opening hash before returning `STAMPED` or `NOT_STAMPED`.",
    "8. Classify only from `record.kind`. Return `STAMPED` only after every required gate above succeeds.",
    "",
    "### Result states",
    "",
    "- `STAMPED`: every manifest, canonical-block, runtime, ABI-descriptor, immutable-binding, lookup, record, identity, nonzero-field, proof, route, and any required closing-hash gate succeeds. Current component-runtime equality is reported separately.",
    "- `NOT_STAMPED`: the canonical token, pool, or exclusive-component lookup succeeds and returns zero after any required closing canonical-block check.",
    "- `UNAVAILABLE`: the Router binding does not cover the requested block, the chain is inactive, or required manifest activation data is incomplete.",
    "- `INDETERMINATE`: RPC, ABI, runtime, block, decoding, or cross-check evidence is incomplete or inconsistent.",
    "",
    "Only a successful canonical zero lookup is `NOT_STAMPED`. A timeout, pruned block, malformed response, chain mismatch, unavailable finalized block, or inconsistent nonzero response is `INDETERMINATE`, not an unsafe claim. `ORPHANED` is an event-observation or reorg state, not a point-verification outcome.",
    "",
    "## Discover new launches when needed",
    "",
    "Point verification does not require an indexer. If you need continuous discovery, scan only the canonical Router from `startBlock`, treat logs as candidates, and establish provenance with the point verifier.",
    "",
    "| Event | Full signature | topic0 |",
    "| --- | --- | --- |",
    ...eventRows,
    "",
    "1. Require `eth_chainId == 0x1`, the exact Router emitter, full topic signatures, runtime, ABI, bindings, block range, and finality policy.",
    "2. Backfill bounded `eth_getLogs` chunks from `startBlock` through a finalized boundary. Respect `endBlock` if a future manifest retires this Router.",
    "3. Persist block number and hash, transaction hash and index, and log index as the idempotency key.",
    "4. Correlate the three event types by `launchId`; then reproduce the candidate with getter reads at the same canonical block.",
    `5. Advance a durable checkpoint only through finality. Explicit block reads require at least ${router.finalityConfirmations} confirmations.`,
    "6. Replay an overlap on every run. Prefer EIP-1898 reads with `requireCanonical: true`; after a reorg, rewind to the last common finalized checkpoint and replay.",
    "7. Begin polling or subscription from the overlapping checkpoint so backfill and subsequent subscription have no gap.",
    "",
    "## Protocol fee claim discovery",
    "",
    "The launch feed is not the protocol fee claim queue. The claim inventory follows the exact execution contracts: Classic V2 and V3 coin rows come from complete canonical Launcher event scans while fee execution remains one aggregate claim per verified version hook; Classic V1 remains a legacy aggregate row. Custom V1 replays the complete Registry history and verifies current state, runtime, reward wallet, fee policy and accrued amount at one block. Stock uses the published fixed release asset set. Custom V2 remains unavailable until an exact deployed and finalized release binding exists.",
    "",
    "Unknown, revoked, mismatched or unverified sources block the combined claim instead of being omitted. The live console rescans before every attempt and publishes its machine-readable boundary at https://claimhazard.vercel.app/claim-discovery.json. Positive verified entries are sent only as one wallet-declared atomic batch from the fixed reward wallet.",
    "",
    "## Canonical resources",
    "",
    `- [Discovery document](${resources.discoveryUrl}) — stable entry point that supplies \`manifestUrl\`.`,
    `- [Deployment manifest](${resources.manifestUrl}) — chain, Router, start block, runtime, immutable bindings, event topics, ABI URL, and ABI digest.`,
    `- [Hosted Router ABI](${resources.abiUrl}) — hash the exact downloaded bytes and match \`${resources.abiSha256}\`.`,
    `- [GitHub Router reference](${resources.referenceUrl}) — complete point-verification specification and finalized PCAN test case.`,
    `- [Terminal guide](${resources.terminalGuideUrl}) — backfill, checkpoint overlap, reorg, and finality handling.`,
    `- [JSON-RPC verifier](${resources.jsonRpcVerifierUrl}) — dependency-light implementation.`,
    `- [viem verifier](${resources.viemVerifierUrl}) — typed application implementation.`,
    "",
    "## Finalized PCAN vector",
    "",
    "Use this CustomGraph launch as the end-to-end integration vector:",
    "",
    `- transaction: \`${canary.transactionHash}\``,
    `- block: \`${canary.blockNumber}\``,
    `- launchId: \`${canary.launchId}\``,
    `- stampHash: \`${canary.stampHash}\``,
    `- token: \`${canary.components.token}\``,
    `- hook: \`${canary.components.hook}\``,
    `- initializer: \`${canary.components.initializer}\``,
    `- PoolManager: \`${canary.pool.poolManager}\``,
    `- poolId: \`${canary.pool.poolId}\``,
    `- launchKind: \`${canary.launchKind}\` (Programmable Custom)`,
    "",
    "The token, pool, and exclusive components resolve to the same launch ID and stamp hash. Generic token or pool discovery by a third party is separate from verified Programmable provenance.",
    "",
    "## What verification proves",
    "",
    "A Router record establishes provenance only after the published address, runtime, binding, lookup, and cross-check requirements pass. For its exact recorded pool, successful verification also establishes initialization during the same atomic launch transaction.",
    "",
    "It does not establish safety, tradability, current liquidity or pool state, audit coverage, review status, approval, endorsement, permission to launch, or terminal support. It does not automatically list or label a launch in GMGN, Axiom, FOMO, or any other terminal; each consumer must implement the published verification procedure.",
    "",
    `Router verification is read-only. Launch access is a separate product path from verification: create a wallet-bound key at ${apiKeysUrl} and use ${customLaunchApiOrigin}/v1/custom-launches, or check https://programmable.market/docs/creators/launch for other current launch paths. The provenance reference alone grants neither access nor launch authorization.`,
  ].join("\n");
}

export const developerDocsMarkdown = buildDeveloperDocsMarkdown();

export function buildProgrammableHomeMarkdown(): string {
  return [
    "# Programmable",
    "",
    "> Discover verified launches, understand what their Uniswap v4 hooks do, and use the website to create or interact with token and outcome markets.",
    "",
    "Programmable brings token discovery, launch creation, market context, creator pages, trading preparation, profiles, and reward claims into one website. Human-facing wallet actions still require an explicit user confirmation.",
    "",
    "## Explore verified launches",
    "",
    "Explore lists verified Classic V3 launches, Registry-verified Custom launches, and finalized Router-stamped Custom provenance entries. The official Programmable main token is the sole authorized Classic V2 exception.",
    "",
    `Official main token: ${V4_TOKEN_ADDRESS}`,
    "",
    "All other Classic V1 or V2 launches, every Stock family, and Custom launches without successful Registry verification or a finalized verified Router stamp remain excluded. Router-stamped entries remain provenance-only Custom entries, not a separate product category or review claim.",
    "",
    "Market data is optional enrichment. A market-data provider outage can remove prices or charts, but it must not remove an already verified token identity from Explore.",
    "",
    "## Main destinations",
    "",
    "- Explore: https://programmable.market/explore",
    "- Prediction Markets: https://programmable.market/markets",
    "- Create: https://programmable.market/launch",
    "- Profile, projects, and rewards: https://programmable.market/profile",
    `- Custom Launch API keys: ${apiKeysUrl}`,
    "- Documentation: https://programmable.market/docs",
    "- Developer documentation: https://programmable.market/docs/developers",
    "",
    "## Prediction Markets",
    "",
    "Prediction Markets is separately versioned. Use its canonical repository for current networks, market types, economics, resolution rules, contract addresses, and release status instead of copying release constants into this product overview.",
    "",
    `- Canonical source and releases: ${PROGRAMMABLE_PUBLIC_REPOSITORIES.predictionMarkets}`,
    "",
    "## Machine-readable resources",
    "",
    "- Agent index: https://programmable.market/llms.txt",
    "- Full agent context: https://programmable.market/llms-full.txt",
    "- Developer API description: https://programmable.market/openapi.json",
    "- Developer guide as Markdown: https://programmable.market/docs/developers.md",
    "- Sitemap: https://programmable.market/sitemap.xml",
    "",
    "## Safety boundary",
    "",
    "A verified Programmable identity is provenance, not a promise of safety, liquidity, price accuracy, tradability, audit coverage, endorsement, or future value. Do not sign, submit, or claim a transaction on a user's behalf without their explicit wallet confirmation.",
  ].join("\n");
}

export const programmableHomeMarkdown = buildProgrammableHomeMarkdown();

export function buildProgrammableLlmsIndex(): string {
  return [
    "# Programmable",
    "",
    "> Agent guide for API-key Custom launch preparation and verified Programmable launch discovery.",
    "",
    "## When to use Programmable",
    "",
    "- Discover verified Classic V3 launches, Registry-verified Custom launches, and finalized Router-stamped Custom provenance entries.",
    "- Open the current Prediction Markets product and its separately versioned canonical release record.",
    "- Look up one displayed token by Ethereum address without depending on optional market enrichment for identity.",
    "- Understand the public scope, creator information, launch provenance, and available market context before directing a user to the website.",
    "- Integrate a read-only terminal, wallet, scanner, catalog, or research tool with the documented public endpoints.",
    `- Prepare a Custom launch with a wallet-bound API key from ${apiKeysUrl} and \`POST ${customLaunchApiOrigin}/v1/custom-launches\`.`,
    "- Direct a human to trade, manage a project, claim rewards, or sign a prepared launch transaction through the website. Those wallet actions require explicit wallet authority.",
    "",
    "## Do not use Programmable to infer",
    "",
    "- Safety, endorsement, audit coverage, liquidity, price accuracy, tradability, or future value from a verified identity.",
    "- Public eligibility for Classic V1, other Classic V2 launches, any Stock family, or a Custom launch without successful Registry verification or a finalized verified Router stamp.",
    "- Transaction authority from an API key. The Custom Launch API validates and prepares an exact action, but it cannot sign or broadcast for the controller wallet.",
    "- Fee claiming or buyback management from a V1 key. `fees:claim` and `buybacks:manage` are reserved and disabled.",
    "- Sponsored or autonomous Prediction Market creation unless the active canonical release explicitly enables it and publishes the required service boundary.",
    "",
    "## Public identity scope",
    "",
    "- Public catalog: verified Classic V3 launches, Registry-verified Custom launches, finalized Router-stamped Custom provenance entries, and the sole official Classic V2 main-token exception.",
    `- Official main token: ${V4_TOKEN_ADDRESS}.`,
    "- Excluded: all other Classic V1 or V2 launches, every Stock family, and Custom launches without a verified Registry record or finalized Router stamp.",
    "- Finalized Router records can surface as provenance-only Custom entries after 64 confirmations. Router is an evidence source, not a separate category, review, audit, liquidity, or safety claim.",
    "- Dexscreener is optional market enrichment. An enrichment outage must not hide an already verified token identity.",
    `- Prediction Markets uses separate versioned release records. Current source and release status: ${PROGRAMMABLE_PUBLIC_REPOSITORIES.predictionMarkets}.`,
    "",
    "## Public machine-readable resources",
    "",
    "- OpenAPI: https://programmable.market/openapi.json",
    `- Create or revoke API keys: ${apiKeysUrl}`,
    `- Create a Custom launch: POST ${customLaunchApiOrigin}/v1/custom-launches`,
    `- List wallet-owned Custom launches: GET ${customLaunchApiOrigin}/v1/custom-launches`,
    `- Read a Custom launch: GET ${customLaunchApiOrigin}/v1/custom-launches/{launchId}`,
    "- API index: https://programmable.market/api",
    "- Explore catalog: https://programmable.market/api/explore",
    "- Prediction Markets: https://programmable.market/markets",
    `- Prediction Markets source and releases: ${PROGRAMMABLE_PUBLIC_REPOSITORIES.predictionMarkets}`,
    "- Token lookup: https://programmable.market/api/explore/token?address=0x7987f03462200b3D8A072E02C89A8A41dCB124EE",
    "- Custom Registry readiness: https://programmable.market/api/custom-launch/registry/v2/readiness",
    "- Custom Registry manifest: https://programmable.market/api/custom-launch/registry/v2/manifest",
    "- Sitemap: https://programmable.market/sitemap.xml",
    "- Human documentation: https://programmable.market/docs",
    "- Developer documentation: https://programmable.market/docs/developers",
    "- Developer Markdown: https://programmable.market/docs/developers.md",
    "",
    "## Provenance evidence reference",
    "",
    "> Canonical read-only provenance reference for Router-stamped Programmable Classic and Programmable Custom launches on Ethereum. Finalized Router evidence can feed the existing Custom category; it does not create a separate category or imply review, audit, liquidity, or safety.",
    "",
    `- Deployment manifest: ${resources.manifestUrl}`,
    `- Router: ${router.address}`,
    `- startBlock: ${router.startBlock}`,
    `- runtimeCodeHash: ${router.runtimeCodeHash}`,
    `- ABI: ${resources.abiUrl}`,
    `- ABI SHA-256: ${router.abiSha256}`,
    `- GitHub reference: ${resources.referenceUrl}`,
    `- Terminal guide: ${resources.terminalGuideUrl}`,
    `- Human overview: https://programmable.market${developerDocsPath}`,
    `- Markdown overview: https://programmable.market${developerDocsMarkdownPath}`,
    "",
    "## Required Router-evidence interpretation",
    "",
    "- Only launches executed and stamped through this Router inside its published block range have Router V1 provenance. Launches before `startBlock`, and direct factory calls outside the Router even when later, do not.",
    "- Map kind 1 to Programmable Custom and kind 2 to Programmable Classic. Kind 0 is invalid.",
    "- Verify token, `(PoolManager, poolId)`, or exclusive-component identity with canonical getter reads at one finalized block.",
    "- Before returning a result, require complete live or retired-in-range manifest activation data; one concrete block number and hash; Router runtime and ABI-byte hashes; all getter selectors, event topics, and indexed layouts; `CHAIN_ID()` plus all six immutable binding getters; and the permit authority, Graph Factory, and PoolManager runtimes.",
    "- Use EIP-1898 canonical block-hash reads where supported. For number-bound reads, require the closing block hash to equal the opening hash before returning `STAMPED` or `NOT_STAMPED`.",
    "- Remote RPC URLs must use HTTPS. Plain HTTP is accepted only for loopback development endpoints.",
    "- A nonzero result still requires exact query identity, valid record address encoding, nonzero bytes32 identity and commitment fields, matching `stampProof` for token or exclusive-component queries, and the launch-kind route rule: immutable Graph Factory for `CustomGraph`, permit-bound recorded launcher and runtime for `Classic`.",
    "- Current component-runtime equality is a separate drift signal, not a historical provenance gate.",
    "- A shared Classic hook is not a launch identifier.",
    "- A successful canonical zero lookup is not stamped. RPC failure or inconsistent evidence is not a negative result.",
    "- After manifest and ABI bootstrap, point verification needs an Ethereum provider only. Indexing, Supabase, a Programmable launch-feed API, and an application server are not trust dependencies.",
    "- Event backfill and checkpoint-based subscription are optional for continuous discovery; logs are candidates until getter verification succeeds.",
    "- Protocol fee claim discovery is a separate index: complete Classic Launcher and Custom Registry scans plus the fixed Stock release set. Unknown or unverified sources fail closed, and Custom V2 stays unavailable until its exact deployed release is finalized.",
    "- The live claim boundary is published at https://claimhazard.vercel.app/claim-discovery.json and requires one wallet-declared atomic batch from the fixed reward wallet.",
    "- A Router record establishes provenance only after the required address, runtime, binding, lookup, and cross-check verification passes. It does not establish safety, tradability, current liquidity, audit coverage, endorsement, terminal support, or launch authorization.",
    `- Launch access is a separate product path from this provenance reference. Use ${apiKeysUrl} for API-first Custom launch access or check https://programmable.market/docs/creators/launch for other current paths; the provenance reference alone grants neither access nor launch authorization.`,
  ].join("\n");
}

export const programmableLlmsIndex = buildProgrammableLlmsIndex();

export function buildProgrammableLlmsFullFallback(): string {
  return [
    buildProgrammableLlmsIndex(),
    "",
    "## Expanded Router overview",
    "",
    `This overview is not the normative verification algorithm. Implement against the canonical GitHub Router reference: ${resources.referenceUrl}`,
    "",
    buildDeveloperDocsMarkdown(),
  ].join("\n");
}

export const programmableLlmsFullFallback = buildProgrammableLlmsFullFallback();
