export const PROGRAMMABLE_AGENT_SETUP_LINKS_V1 = Object.freeze({
  discovery: "https://programmable.market/.well-known/programmable.json",
  capabilities: "https://api.programmable.market/v3/capabilities",
  preflight: "https://api.programmable.market/v3/custom-launches/preflight",
  remediation:
    "https://programmable.market/policies/custom-launch-agent-remediation-v1.json",
  packConfigSchema:
    "https://programmable.market/schemas/custom-launch/v3/pack-config.json",
  cli: "https://github.com/0xprogrammable/PROGRAMMABLE/releases/download/programmable-launch-v3.3.7/programmable-launch-3.3.7.tgz",
  guide:
    "https://programmable.market/docs/developers/custom-launch#existing-project-integration",
  openApi: "https://programmable.market/openapi/custom-launch-v3.json",
  openApiV2Compatibility:
    "https://programmable.market/openapi/custom-launch-v2.json",
  openApiV1Compatibility:
    "https://programmable.market/openapi/custom-launch-v1.json",
});

export const PROGRAMMABLE_AGENT_SETUP_TEXT_V1 = Object.freeze([
  "Programmable Custom Launch agent setup",
  "",
  "Use the preconfigured $PROGRAMMABLE_API_KEY from encrypted secrets or the environment. Never paste the key into chat, a prompt, source code, or command history.",
  "The API key grants API access only. It does not contain policy or integration instructions.",
  "",
  `Start here: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.discovery}`,
  `Public capabilities: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.capabilities}`,
  `Non-persisting preflight: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.preflight}`,
  `Existing-project remediation contract: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.remediation}`,
  `Pack-config schema: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.packConfigSchema}`,
  "Fetch discovery and public GET /v3/capabilities first. Bind the project to the returned profile revision; do not infer support from an older response.",
  "Read customLaunchApi.agentIntegration, then follow its remediation catalog, guide, OpenAPI and pinned CLI release before changing the project.",
  `Install: npm install --global ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.cli}`,
  `Release asset: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.cli}`,
  `Guide: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.guide}`,
  `Public V3 OpenAPI: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.openApi}`,
  `V2 read compatibility and fresh-write fence: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.openApiV2Compatibility}`,
  `V1 read compatibility and fresh-write fence: ${PROGRAMMABLE_AGENT_SETUP_LINKS_V1.openApiV1Compatibility}`,
  "Use only the current V3.3 profile for a new submission. Fresh V2 and V1 POSTs are permanently read-only and return non-retryable 409 CUSTOM_LAUNCH_V2_READ_ONLY or 409 CUSTOM_LAUNCH_V1_READ_ONLY; their schemas and reads remain available for historical resources.",
  "Profile 3.4.0 and CLI 3.3.8 are preparatory, not live, released, installable or accepted for fresh writes. Live/default discovery remains profile 3.3.0 and the pinned CLI 3.3.7 asset until the backend and .well-known document independently activate the pending profile. Do not install or submit the source-tree candidate.",
  "V2 detail reads are observation-only for prepared or simulating resources. GET cannot advance simulation or authorization or expose a new walletTransaction; existing authorized and submitted reconciliation and finalized reads remain available.",
  "Before pack, collect the required project name and symbol, a meaningful description, one canonical website, one canonical X profile, and a non-empty local PNG, JPEG, WebP or GIF plus its canonical public HTTPS, IPFS or Arweave URI. Documentation, Telegram, Discord, GitHub and other links remain optional. Never invent metadata or a public image URI.",
  "The CLI derives the image content digest, media type, byte length and dimensions from the local bytes and binds the complete canonical project metadata into the request and launch identity. Never handwrite these derived fields. The website shows the same metadata read-only before either wallet step; changing it requires a newly packed request.",
  "Inspect the exact public source revision and create programmable-launch.config.json with schemaVersion programmable.launch-pack-config.v3. Validate it against the pack-config schema. Follow the generic catalog for funding, nonce/r/s/v ABI argument paths, liquidity and diagnostics. There is no project allowlist or private approval path.",
  "programmable-launch pack --config programmable-launch.config.json --output launch.json",
  "programmable-launch validate launch.json --config programmable-launch.config.json --remote",
  "Preflight consumes no launch-creation quota or durable reservation: quotaConsumed, nonceAllocated and persisted must all be false. The authenticated HTTP call still consumes its ordinary route rate budget, including a partner credential's prepareRequestsPerHour budget. It never creates a wallet action. walletSignatureRequiredLater is true and walletBroadcastByService is false. Local CLI checks and remote preflight prepare and classify exact bytes; they are not the launch decision.",
  "Submit only the byte-identical current V3.3 request when launchEligibility.deployable is true. The API server remains the decision authority after submission. It independently enforces objective static hard blocks and exact Router simulation before exposing any wallet handoff. A needs_evidence or not_executed result is not a pass and cannot support a positive behavior, fee, liquidity or routability claim; an authenticated executed failure blocks the handoff. Client, model or attestation output cannot promote or bypass a server result. For unsupported, fix the typed hard-block remediation and rebuild instead of asking for a bypass.",
  "programmable-launch submit launch.json --config programmable-launch.config.json",
  "programmable-launch status REQUEST_UUID --watch --until authorized",
  "Use this state machine: pack -> validate --remote -> submit -> server decision -> status --watch --until authorized -> wallet -> status --watch --until finalized. Remote validation first fails closed unless the public profile, revision, version, routes and authentication boundary match this CLI, then sends the same exact V3.3 bytes to non-persisting preflight that consumes no launch-creation quota. Submit only the byte-identical V3.3 request produced by pack and keep the CLI journal and Idempotency-Key unchanged for retries.",
  "Wallet keys require launchWallet to equal their wallet binding. Partner roots and subkeys may select the exact controller in the immutable request but cannot sign for it. On both list and single-resource status reads, a partner root reads every launch attributed to its partner. A subkey reads only its stable lineage, rotation preserves that lineage history for the replacement, the revoked predecessor cannot authenticate, and a separately issued subkey cannot read root or sibling launches. The current Router V1 permit-reissue disposition endpoint accepts wallet keys only; a partner launch recovers by packing and submitting a new request.",
  "If profile 3.4.0 is later activated, fresh packs require complete project metadata plus declarative behaviorScenarioInputs. The CLI derives behaviorScenarioInputsHash and binds it into launchIntentHash. Inputs may name only exact prepared targets, poolManager or the fixed v4-actions-v1 harness and may not contain scripts, URLs, assertions, expected results, statuses or runner parameters. Until activation, fresh writes remain exact profile 3.3.0; older bytes retain only their immutable read and byte-identical retry semantics.",
  "If status is action_required, follow the resource remediation, fix the exact source or config finding, rebuild and submit a new immutable request. Do not ask for a manual allowlist or retry unchanged bytes.",
  "Follow a walletHandoffUrl only after the server-authored resource is authorized; client, CLI or model output cannot create that state. Missing behavior execution leaves behavior, fee, liquidity and routability claims unverified; an authenticated executed failure blocks the handoff. If the selected lane is an open arbitrary-custom-hook lane, it carries no automatic Programmable-fee claim. A 10 bps claim exists only for a fee-certified profile or adapter and its exact stamped PoolKey; arbitrary custom hooks are not automatically fee-enforced.",
  "If profile 3.4.0 is later activated, wallet handoff additionally requires exact source, compiler and graph binding, static admission, a platform admission receipt, exact Router simulation, verified behavior evidence and verified exact 10 bps fee-path evidence. Missing, not-configured or unavailable execution cannot authorize; executed behavior failure or a mutable fee path blocks terminally. This describes a pending server gate, not current activation or evidence. The server owns every assertion and verdict, and legacy resources retain their stored evidence state.",
  "When the selected lane uses applicant buy or sell rates, each rate is capped at 100000 hundredths of a bip, equal to 1000 bps or 10 percent. The server enforces that cap in additive-platform-share and inclusive-selected-total modes. The separate platform value is 1000 hundredths of a bip, equal to 10 bps, and creates a claim only in the fee-certified lane.",
  "If status is awaiting_funding_authorization, open only the same-origin walletHandoffUrl and stop for the connected controller to review and sign the exact funding typed data in the website. At authorized, stop again for the controller to review and send the exact Router transaction. Respect expiresAt and secondsRemaining; never reuse an expired handoff. Then use status to follow that single resource to a terminal state.",
  "The CLI never signs or broadcasts.",
].join("\n"));
