export const PROJECTOR_MAXIMUM_RUNTIME_ROUNDS = 8;
export const PROJECTOR_MAXIMUM_CANDIDATES_PER_PAGE = 32;
export const PROJECTOR_MAXIMUM_CANDIDATES_PER_CYCLE =
  PROJECTOR_MAXIMUM_RUNTIME_ROUNDS * PROJECTOR_MAXIMUM_CANDIDATES_PER_PAGE;
